In [1]:
import numpy as np
import torch

torch.__version__

'1.7.0+cu101'

In [6]:
t = np.array([0, 1, 2, 3, 4,])
print(t)
print(t.shape)
print(t.ndim)
print()

t = np.array([[1,2,3],[4,5,6]])
print(t)
print(t.shape)
print(t.ndim)

[0 1 2 3 4]
(5,)
1

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [7]:
t = torch.FloatTensor([1,2,3,])
print(t)
print(t.shape)
print(t.ndim)

tensor([1., 2., 3.])
torch.Size([3])
1


In [8]:
#max argmax
t = torch.FloatTensor([[1,2], [3,4]])
print(t.max())
print(t.max(dim=0)) # max, argmax
print(t.max(dim=0)[0]) # max
print(t.max(dim=0)[1]) # argmax

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([1, 1])


In [19]:
t = np.array([[1,2],[3,4]])
print(t.shape)
ft = torch.FloatTensor(t)
print(ft.shape)

#view?
print(ft.view(-1)) #tensor 형태 변경

(2, 2)
torch.Size([2, 2])
tensor([1., 2., 3., 4.])


In [23]:
#Sactter : One Hot encoding 변수를 임의로 채울수 있음
lt = torch.LongTensor([[0],[1],[2],[0]])
print(lt)
print()

one_hot = torch.zeros(4,3)
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[0],
        [1],
        [2],
        [0]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


In [24]:
#Concattenation
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [25]:
#in-place operation : 원본값을 변경함
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
