In [ ]:
# https://github.com/jukyellow/PyTorch/blob/master/lab-04_2_load_data.ipynb

In [1]:
nums = [0, 1, 2, 3, 4]
print(nums)

print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8, 9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [2]:
import numpy as np

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)

print(b[:, 1])
print(b[-1])
print(b[-1, :])
print(b[-1, ...])
print(b[0:2, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


In [3]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape) # x_data shape
print(len(x_data))  # x_data 길이
print(x_data[:5])   # 첫 다섯 개

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# For reproducibility
torch.manual_seed(1)

In [6]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b # or .mm or @

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 26811.960938
Epoch    1/20 Cost: 9920.530273
Epoch    2/20 Cost: 3675.298340
Epoch    3/20 Cost: 1366.260498
Epoch    4/20 Cost: 512.542480
Epoch    5/20 Cost: 196.896637
Epoch    6/20 Cost: 80.190987
Epoch    7/20 Cost: 37.038696
Epoch    8/20 Cost: 21.081343
Epoch    9/20 Cost: 15.178760
Epoch   10/20 Cost: 12.993679
Epoch   11/20 Cost: 12.183023
Epoch   12/20 Cost: 11.880535
Epoch   13/20 Cost: 11.765958
Epoch   14/20 Cost: 11.720851
Epoch   15/20 Cost: 11.701438
Epoch   16/20 Cost: 11.691514
Epoch   17/20 Cost: 11.685116
Epoch   18/20 Cost: 11.680005
Epoch   19/20 Cost: 11.675380
Epoch   20/20 Cost: 11.670952


In [7]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [16]:
# 데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20 * 3
for epoch in range(nb_epochs+1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/60 Cost: 37021.359375
Epoch    1/60 Cost: 13709.822266
Epoch    2/60 Cost: 5090.887695
Epoch    3/60 Cost: 1904.212769
Epoch    4/60 Cost: 725.994202
Epoch    5/60 Cost: 290.357880
Epoch    6/60 Cost: 129.275269
Epoch    7/60 Cost: 69.702209
Epoch    8/60 Cost: 47.660400
Epoch    9/60 Cost: 39.494938
Epoch   10/60 Cost: 36.459793
Epoch   11/60 Cost: 35.321587
Epoch   12/60 Cost: 34.884674
Epoch   13/60 Cost: 34.707153
Epoch   14/60 Cost: 34.625511
Epoch   15/60 Cost: 34.579365
Epoch   16/60 Cost: 34.546280
Epoch   17/60 Cost: 34.518116
Epoch   18/60 Cost: 34.491722
Epoch   19/60 Cost: 34.466019
Epoch   20/60 Cost: 34.440624
Epoch   21/60 Cost: 34.415314
Epoch   22/60 Cost: 34.390079
Epoch   23/60 Cost: 34.364899
Epoch   24/60 Cost: 34.339684
Epoch   25/60 Cost: 34.314545
Epoch   26/60 Cost: 34.289391
Epoch   27/60 Cost: 34.264271
Epoch   28/60 Cost: 34.239178
Epoch   29/60 Cost: 34.214100
Epoch   30/60 Cost: 34.189060
Epoch   31/60 Cost: 34.164005
Epoch   32/60 Cost: 34.1390

In [10]:
# Dataset and DataLoader
from torch.utils.data import Dataset

class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]
    def __len__(self):
        return len(self.x_data)
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [41]:
from torch.utils.data import DataLoader

dataset =  CustomDataset()
print(len(dataset))

p_batch_size = 2
dataloader = DataLoader(
    dataset,
    batch_size = p_batch_size,
    shuffle = True
)
print(len(dataloader))

5
3


In [42]:
# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1) :
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        #print('samples:', samples)

        # H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 업데이트
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        result_pred_y = 0, 0
        if p_batch_size < 2: result_pred_y = int(prediction.squeeze().detach()), int(y_train.squeeze().detach())
        else: result_pred_y = prediction.squeeze().detach(), y_train.squeeze().detach()
            
        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f} pred/y: {}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item(),
            result_pred_y
        ))

Epoch    0/20 Batch 1/3 Cost: 31202.828125 pred/y: (tensor([-11.2180,  -8.7524]), tensor([180., 152.]))
Epoch    0/20 Batch 2/3 Cost: 14273.857422 pred/y: (tensor([68.2314, 73.8820]), tensor([185., 196.]))
Epoch    0/20 Batch 3/3 Cost: 1823.973267 pred/y: (tensor(99.2920), tensor(142.))
Epoch    1/20 Batch 1/3 Cost: 1182.393188 pred/y: (tensor([111.7508, 157.9241]), tensor([142., 196.]))
Epoch    1/20 Batch 2/3 Cost: 365.984070 pred/y: (tensor([162.5919, 136.8394]), tensor([185., 152.]))
Epoch    1/20 Batch 3/3 Cost: 103.585655 pred/y: (tensor(169.8223), tensor(180.))
Epoch    2/20 Batch 1/3 Cost: 47.024708 pred/y: (tensor([134.4736, 189.8843]), tensor([142., 196.]))
Epoch    2/20 Batch 2/3 Cost: 17.776108 pred/y: (tensor([179.4570, 177.8029]), tensor([185., 180.]))
Epoch    2/20 Batch 3/3 Cost: 0.226385 pred/y: (tensor(152.4758), tensor(152.))
Epoch    3/20 Batch 1/3 Cost: 7.551175 pred/y: (tensor([138.1451, 179.5082]), tensor([142., 180.]))
Epoch    3/20 Batch 2/3 Cost: 4.884409 pred