In [ ]:
# https://datascienceschool.net/02%20mathematics/02.04%20%EC%84%A0%ED%98%95%20%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D%EA%B3%BC%20%EC%97%AD%ED%96%89%EB%A0%AC.html

# 선형 연립방정식

복수의 미지수를 포함하는 복수의 선형 방정식을 선형 연립방정식(system of linear equations) 또는 연립일차방정식이라고 한다.  
<br>
\begin{align}
Ax = b  
\tag{2.4.5}
\end{align}
<br>
A,x,b  는 각각 **계수행렬(coefficient matrix), 미지수벡터(unknown vector), 상수벡터(constant vector)**라고 부른다.  
<br>
\begin{split}
\begin{align}
A = 
\begin{bmatrix}
 1 & 1 & 0 \\
 0 & 1 & 1 \\
 1 & 1 & 1 \\
\end{bmatrix}, \;\;\;
x = \begin{bmatrix}
x_1 \\ x_2 \\ x_3
\end{bmatrix}, \;\;\;
b = \begin{bmatrix}
2 \\ 2 \\ 3
\end{bmatrix}
\tag{2.4.7}
\end{align}
\end{split}
<br>
\begin{align}
x = \dfrac{b}{A}
\tag{2.4.8}
\end{align}
<br>
그러나 행렬에서는 나눗셈이 정의되지 않으므로 이 방법은 사용할 수 없다. 행렬에서는 나눗셈 대신 역행렬이라는 것을 사용한다.  


# 역행렬
정방 행렬 A에 대한 역행렬(inverse matrix) A−1은 원래의 행렬 A와 다음 관계를 만족하는 정방 행렬을 말한다. I는 항등 행렬(identity matrix)이다.  
<br>
\begin{align}
A^{-1} A = A A^{-1} = I  
\tag{2.4.9}
\end{align}

# 역행렬의 성질
\begin{align}
(A^{T})^{-1} = (A^{-1})^{T}  
\tag{2.4.11}
\end{align}



# 역행렬의 계산
\begin{split} 
\begin{align}
A^{-1} = \dfrac{1}{\det (A)} C^T = \dfrac{1}{\det (A)} 
\begin{bmatrix}
C_{1,1} & \cdots & C_{N,1}  \\
\vdots  & \ddots & \vdots   \\
C_{1,N} & \cdots & C_{N,N}  \\
\end{bmatrix}
\tag{2.4.14}
\end{align}
\end{split}
<br>
이 식에서 Ci,j는 A의 i,j번째 원소에 대해 정의한 코팩터(cofactor)다.  
코팩터로 이루어진 행렬 C을 **여인수행렬(matrix of cofactors, 또는 cofactor matrix, comatrix)**이라고 한다. 또 여인수행렬의 전치행렬 CT를 어드조인트행렬(adjoint matrix, adjugate matrix, 수반행렬)이라고 하며 **adj(A)**로 표기하기도 한다.  

In [1]:
import numpy as np

A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
print(A)

Ainv = np.linalg.inv(A)
print(Ainv)

[[1 1 0]
 [0 1 1]
 [1 1 1]]
[[ 0. -1.  1.]
 [ 1.  1. -1.]
 [-1.  0.  1.]]


# 역행렬과 선형 연립방정식의 해
\begin{align}
Ax = b
\tag{2.4.26}
\end{align}
<br>
\begin{align}
x = A^{-1}b  
\tag{2.4.29}
\end{align}


In [3]:
b = np.array([[2], [2], [3]])
print(b)

x = Ainv @ b
print(x)

print(A @ x - b)

[[2]
 [2]
 [3]]
[[1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]]


In [4]:
# lstsq() 명령은 행렬 A와 b를 모두 인수로 받고 뒤에서 설명할 최소자승문제(least square problem)의
# 답 x, 잔차제곱합(residual sum of squares) resid, 랭크(rank) rank, 특잇값(singular value) s를 반환한다. 
# 미지수와 방정식의 개수가 같고 행렬 A의 역행렬이 존재하면 최소자승문제의 답과 선형 연립방정식의 답이 같으므로 lstsq() 명령으로 선형 연립방정식을 풀 수도 있다. 
# 최소자승문제, 랭크, 특잇값에 대해서는 뒤에서 자세히 설명할 것이다.

x, resid, rank, s = np.linalg.lstsq(A, b)
print(x)

[[1.]
 [1.]
 [1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


# 미지수의 수와 방정식의 수¶

<br>

# 최소자승문제